apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rddep123
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: read
    spec:
      volumes:
      - name: pv789
        persistentVolumeClaim:
         claimName: pvc789
      containers:
      - name: rdcon
        image: poojabiyani/123img:latest
        volumeMounts:
        - name: pv789
          mountPath: "/var/www/html/fol"
     
  
